#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
auto_upgrade = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#4C566A'
    background = '#E5E9F0'
    leading_diamond = '╭─'

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#4C566A'
    background = '#E5E9F0'
    template = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }}{{ end }}'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#2E3440'
    background = '#81A1C1'
    template = '  </>{{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#2E3440'
    background = '#A3BE8C'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#EBCB8B{{ end }}', '{{ if gt .Ahead 0 }}#B48EAD{{ end }}', '{{ if gt .Behind 0 }}#B48EAD{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = false
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#2E3440'
    background = '#EBCB8B'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' ⚡ {{ if gt .Code 0 }} {{ reason .Code }}{{ else }}{{ end }}'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#2E3440'
    background = '#B48EAD'
    template = '<#B48EAD,transparent></>  {{ .FormattedMs }} <transparent,#B48EAD></>'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#2E3440'
    background = '#81A1C1'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ECEFF4'
    template = '╰─'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#8FBCBB'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
    template = '<#B48EAD>❯</> '

    [blocks.segments.properties]
      always_enabled = true
